<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2fQBq8a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2fQBq8a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2fQBq8a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2fQBq8a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2fQBq8a\App_KernelDevDebugContainer([
    'container.build_hash' => '2fQBq8a',
    'container.build_id' => 'e8d06966',
    'container.build_time' => 1613008154,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2fQBq8a');
