<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQPLuT2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQPLuT2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRQPLuT2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRQPLuT2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRQPLuT2\App_KernelDevDebugContainer([
    'container.build_hash' => 'RQPLuT2',
    'container.build_id' => 'a916076d',
    'container.build_time' => 1613040440,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQPLuT2');
